### PR TITLE
Readme: add installation instructions and examples

### PR DESCRIPTION
**Pull request by oliver-sanders**
Should suffice for now.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
(After this we'll need to do a happy new change + an update to CHANGES.md.)

**Comment by oliver-sanders** [comment]
I've got `pytest` to run on all `.md` files so that the python examples in the `README.md` file get tested. Easy enough.

There are, however, some console examples which will go untested. As this is a problem we have elsewhere in Rose & Cylc I though it might be worth a look-in now that we are using an extendible testing framework.

So ... https://github.com/oliver-sanders/pytest_shelltest

**Comment by matthewrmshin** [comment]
Is this sufficient to close #47?

**Comment by kinow** [comment]
> Is this sufficient to close #47?

+1 from me. We can close that one now and add more to the documentation based on user/dev feedback later IMO

**Pull request merged**
