### PR TITLE
Fix tests on non-UTC system timezones

### LINKED ISSUE #116: Our tests run only on UTC, and fail on other TZ's like NZ
Hi,

Looks like our tests were written for UTC only. The following tests fail when running the tests in NZ time zone.

```
isodatetime/tests/test_00.py::TestSuite::test_timepoint_strftime_strptime FAILED
isodatetime/tests/test_datetimeoper.py::TestDateTimeOperator::test_process_time_point_str_now_0 FAILED
isodatetime/tests/test_datetimeoper.py::TestDateTimeOperator::test_process_time_point_str_ref_0 FAILED
isodatetime/tests/test_datetimeoper.py::TestDateTimeOperator::test_process_time_point_str_x FAILED
```

Left the `test_timepoint` running for a few minutes and got no error.

We should handle testing in any time zone. If a test is handling time zones, then these must be parameters to the tests.

Even better, we can have tests running on multiple time zones. That way we would reduce the chances of having issues like #89.

### PR DESCRIPTION
**Pull request by MetRonnie**
Closes #116

### CODE REVIEW

**Comment by MetRonnie** [comment]
Waiting for #159 to hopefully let the tests pass on Travis

**Comment by oliver-sanders** [comment]
> We just need to sort out the Travis issue

Hopefully rebase on #159 should do it.

**Comment by MetRonnie** [comment]
Is the code coverage check actually working? (I have no experience with Codecov)
[From Travis](https://travis-ci.org/github/metomi/isodatetime/jobs/692486574):
```
$ "${RUN_COVERAGE:-false}" && bash <(curl -s https://codecov.io/bash)
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-20200430-d757c17

==> Travis CI detected.
    project root: .
    Fixing merge commit SHA
    Yaml found at: .codecov.yml
==> Running gcov in . (disable via -X gcov)
==> Python coveragepy exists disable via -X coveragepy
    -> Running coverage xml
    No data to report.
==> Searching for coverage reports in:
    + .
--> No coverage report found.
    Please visit http://docs.codecov.io/docs/supported-languages
Done. Your build exited with 0.
```

**Comment by wxtim** [comment]
> Check with @oliver-sanders but I think it's been flaky/broken for at least 18 months.

**Comment by oliver-sanders** [comment]
No coverage would appear to be broken, it last updated one year ago - https://codecov.io/gh/metomi/isodatetime/commits.

Will raise an issue to fix, can ignore for this PR.

**Pull request merged**
